version: "3.9"

services:
  db:
    image:  arm64v8/mysql:9.3.0
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    ports: 
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports: 
      - "3000:80"
    depends_on:
      - backend
    environment:
      - API_URL=http://backend:8000/api/
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DB_HOST=db
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=secret
    ports:
      - "8000:8000"
    command: >
      bash -c "
                composer install &&
                php artisan migrate --force &&
                php artisan serve --host=0.0.0.0 --port=8000
            "
    depends_on:
      - db
volumes:
  dbdata:

